name: data_entry_app
description: Servicios Geológicos IMEx.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.5+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_launcher_icons: ^0.11.0
  http: ^0.13.3
  flutter_dotenv: ^5.0.2
  cool_alert: ^1.0.2
  shared_preferences: ^2.0.8
  flutter_overlay_loader: ^2.0.0
  shrink_sidemenu: ^2.0.0+1-null-safety
  liquid_ui: ^1.0.0+9
  flutter_onboard: ^2.0.0
  splash_screen_view: ^3.0.0
  connectivity: ^3.0.6
  date_format: ^2.0.4
  select_form_field: ^2.2.0
  bs_flutter_inputtext: ^1.1.1
  data_table_2: ^2.1.1
  datetime_picker_formfield: ^2.0.0
  file_picker: ^4.2.7
  image_picker: ^0.8.4+4
  photo_view: ^0.14.0
  crop_your_image: ^0.7.2
  path_provider: ^2.0.8
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  extended_image: ^6.0.1
  image_editor: ^1.0.2
  sqflite_common_ffi: ^2.1.0+1
  drift: ^2.4.2
  connectivity_plus: ^3.0.3
  msix: ^3.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffb13b"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icon/
    - assets/images/
    - assets/images/logos/
    - assets/images/bg/
    - assets/images/onboard/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoCondensed-Regular
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#BB6000"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  image: assets/icon/icon.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'